<?php

/**
 * @file
 * Adds test module hook.
 */

/**
 * Implements hook_domain_source_path_alter().
 *
 * @see \domain_source_form_validate
 */
function domain_source_test_domain_source_alter(string &$source, string $path, array $options): void {
  // Always make our test REST links go to the primary domain.
  var_dump($path);
  $parts = explode('/', $path);
  if (isset($parts[1]) && $parts[1] === 'domain-format-test') {
    \Drupal::entityTypeManager()->getStorage('domain');
    $source = \Drupal::entityTypeManager()->getStorage('domain')->loadDefaultDomain();
  }
}
