services:
  domain_config.overrider:
    class: Drupal\domain_config\DomainConfigOverrider
    tags:
      - { name: config.factory.override, priority: -150}
    arguments: ['@config.storage', '@module_handler']

  domain_config.library.discovery.collector:
    decorates: library.discovery.collector
    class: \Drupal\domain_config\DomainConfigLibraryDiscoveryCollector
    arguments: ['@cache.discovery', '@lock', '@library.discovery.parser', '@theme.manager']
    tags:
      - { name: needs_destruction }
    calls:
      - [setDomainNegotiator, ['@domain.negotiator']]
  domain_config.factory:
    class: Drupal\domain_config\Config\ConfigFactory
    decorates: config.factory
    decoration_priority: 2
    tags:
      - { name: event_subscriber }
      - { name: service_collector, tag: 'config.factory.override', call: addOverride }
    arguments: ['@config.storage', '@event_dispatcher', '@config.typed', '@domain_config_ui.manager']
